cd path/to/your/repo
mkdir -p .github/workflows
cat > .github/workflows/windows-build.yml << 'EOF'
name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile \
          --add-data "andijan_default_prolong_v2.exe;." \
          --add-data "tashkent_default_prolong_v2.exe;." \
          --name launcher \
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: launcher-exe
        path: dist/launcher.exe
EOF
